### DSCI 510 - Extra Credit
#### Analysis of California Community Colleges
- Feature/Regional Analysis
- Descriptive Map and Plot Visualizations

#### _Scrape Community College Admission Data From Wikipedia_: https://en.wikipedia.org/wiki/List_of_California_Community_Colleges

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
#Connect to Wiki Website
response = requests.get('https://en.wikipedia.org/wiki/List_of_California_Community_Colleges')
soup = BeautifulSoup(response.content, 'html.parser')
response.status_code

200

In [3]:
table = soup.find_all('table')[0]
td = table.find_all('td')


df = pd.DataFrame({0:[], 1:[], 2:[], 3:[], 4:[], 5:[]})
df.rename(columns =dict(enumerate([x.text.strip() for x in table.find_all('th')[1:]])), inplace=True)

start, end, cnt = 0, 6, 0
while end <= 685:
    ls=[]
    row_data = td[start:end]
    for val in row_data:
        ls.append(val.text.strip())
    df.loc[cnt] = ls
    cnt+=1
    start+=6
    end+=6

#### _Feed Colleges to API for Coordinates_ - _API Source_: Google Maps

In [4]:
api_df = pd.DataFrame()
API_key = 'AIzaSyAWXRek5w7WA4qithObH-inNzYL8UYGC0U'
lat_ls, lon_ls, college_ls = [],[], []
for uni in df.College:
    link = f'https://maps.googleapis.com/maps/api/geocode/json?address={uni.replace(" ", "+")}+California&key={API_key}'
    response = requests.get(link)
    addy_data = response.json()
    lat_ls.append(addy_data['results'][0]['geometry']['location']['lat'])
    lon_ls.append(addy_data['results'][0]['geometry']['location']['lng'])
    college_ls.append(uni)

api_df['College'] = college_ls
api_df['Lat'] = lat_ls
api_df['Lon'] = lon_ls

In [5]:
df

,Ranking,College,Total enrollment,Full-time enrollment,Part-time enrollment,Founded
0,1,East Los Angeles College,"36,606","7,090","29,516",1945
1,2,Santa Monica College,"29,999","10,720","19,279",1929
2,3,American River College,"29,701","7,560","22,141",1955
3,4,Santa Ana College,"28,598","3,435","25,163",1915
4,5,Mount San Antonio College,"28,481","10,499","17,982",1946
...,...,...,...,...,...,...
109,110,College of the Siskiyous,"2,533","1,002","1,531",1957
110,111,Lassen College,"2,494",600,"1,894",1925
111,112,Lake Tahoe Community College,"2,426",765,"1,661",1975
112,113,Copper Mountain College,"1,783",750,"1,033",1966
113,114,Feather River College,"1,782",636,"1,146",1968

In [67]:
api_df

                          College        Lat         Lon
0        East Los Angeles College  34.041435 -118.150198
1            Santa Monica College  34.016781 -118.470693
2          American River College  38.651148 -121.346733
3               Santa Ana College  33.757971 -117.888884
4       Mount San Antonio College  34.048749 -117.842132
..                            ...        ...         ...
109      College of the Siskiyous  41.412171 -122.390292
110                Lassen College  40.431527 -120.632581
111  Lake Tahoe Community College  38.926651 -119.972576
112       Copper Mountain College  34.141060 -116.216934
113         Feather River College  39.953068 -120.973011

[114 rows x 3 columns]

#### _Write to SQL Schema_

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
import sqlite3
#Create Database
conn = sqlite3.connect('DS_ExtraCredit.db')
cur = conn.cursor()

cur.execute('PRAGMA foreign_keys = ON')

#Create Tables
cur.execute('DROP TABLE IF EXISTS cc_admissions')

cur.execute('CREATE TABLE cc_admissions \
            (Ranking INT, \
            College TEXT NOT NULL, \
            Total_Enrollment FLOAT, \
            Full_Enrollment FLOAT, \
            Part_Enrollment FLOAT, \
            Founded INT,\
            PRIMARY KEY(College))')

cur.execute('DROP TABLE IF EXISTS cc_coords')
cur.execute('CREATE TABLE cc_coords \
            (College TEXT NOT NULL,\
             Latitude FLOAT,\
             Longitude FLOAT,\
             PRIMARY KEY(College))')

# cur.execute('INSERT INTO cc_admissions VALUES\
#             (1,"SIERRA", 1000, 100, 200)')

#cur.execute('INSERT INTO supplier_groups VALUES(1,"HOE")')
conn.commit()

In [3]:
#Insert CC Admissions Data

#Connect to Wiki Website
response = requests.get('https://en.wikipedia.org/wiki/List_of_California_Community_Colleges')
soup = BeautifulSoup(response.content, 'html.parser')
print(response.status_code)
table = soup.find_all('table')[0]
td = table.find_all('td')

start, end, cnt = 0, 6, 0
colleges = []
while end <= 685:
    ls=[]
    row_data = td[start:end]
    for val in row_data:
        ls.append(val.text.strip())
    ls[0],ls[2], ls[3], ls[4], ls[5]  = int(ls[0]), float(ls[2].replace(',', '')),\
                                    float(ls[3].replace(',', '')),float(ls[4].replace(',', '')), int(ls[5])
    colleges.append(ls[1])

    cur.execute('INSERT INTO cc_admissions VALUES (?, ?, ?, ?, ?, ?)', tuple(ls))
    conn.commit()
    cnt+=1
    start+=6
    end+=6

200

In [5]:
#Insert CC Coordinate Data
API_key = 'AIzaSyAWXRek5w7WA4qithObH-inNzYL8UYGC0U'

for cc in colleges:
    data_lst = [] 
    link = f'https://maps.googleapis.com/maps/api/geocode/json?address={cc.replace(" ", "+")}+California&key={API_key}'
    response = requests.get(link)
    addy_data = response.json()
    data_lst.append(cc)
    data_lst.append(addy_data['results'][0]['geometry']['location']['lat'])
    data_lst.append(addy_data['results'][0]['geometry']['location']['lng'])
    
    cur.execute('INSERT INTO cc_coords VALUES(?, ?, ?)', tuple(data_lst))
    conn.commit()

NameError: name 'uni' is not defined

In [6]:
#run this LAST TO CLOSE
cur.execute('SELECT MAX(Total_Enrollment)  FROM cc_admissions')
print(cur.fetchall())

cur.close()
conn.close()

[(36606.0,)]

In [66]:
cur.execute('SELECT * \
FROM cc_coords')
print(cur.fetchall())

[('East Los Angeles College', 34.0414348, -118.1501982), ('Santa Monica College', 34.0167814, -118.4706934), ('American River College', 38.6511479, -121.3467327), ('Santa Ana College', 33.7579713, -117.888884), ('Mount San Antonio College', 34.0487487, -117.8421321), ('City College of San Francisco', 37.72569, -122.4510797), ('Pasadena City College', 34.1439322, -118.1186338), ('Palomar College', 33.1512505, -117.1821885), ('Fullerton College', 33.8703645, -117.9242123), ('San Diego Mesa College', 32.715738, -117.1610838), ('Long Beach City College', 33.8335679, -118.1345668), ('El Camino Community College District', 33.8842409, -118.3302549), ('Sacramento City College', 37.3541079, -121.9552356), ('De Anza College', 37.3192806, -122.0447919), ('Santa Rosa Junior College', 38.45573, -122.7211551), ('Orange Coast College', 33.6713265, -117.9117079), ('Cerritos College', 33.8850876, -118.095832), ('Fresno City College', 36.7669209, -119.7979063), ('Saddleback College', 33.5538297, -117.6637665), ('Diablo Valley College', 37.9686774, -122.0711537), ('Los Angeles Pierce College', 34.183637, -118.5801887), ('Los Angeles City College', 34.0872692, -118.2924734), ('Southwestern College', 32.6398581, -116.9981916), ('Santa Barbara City College', 34.4051462, -119.6992036), ('Chaffey College', 34.1467226, -117.5708601), ('Los Angeles Valley College', 34.1753399, -118.4189817), ('Grossmont College', 32.8166735, -117.0065725), ('College of the Canyons', 34.4042187, -118.5696313), ('Sierra College', 38.7909585, -121.2108548), ('Riverside City College', 33.9711925, -117.3811035), ('Bakersfield College', 35.4083127, -118.9716398), ('San Joaquin Delta College', 37.9953671, -121.3195528), ('Modesto Junior College', 37.6392595, -120.9970014), ('Rio Hondo College', 34.0190058, -118.0347181), ('San Diego City College', 32.7175697, -117.1508543), ('Cypress College', 33.8278801, -118.0237357), ('Glendale Community College', 34.16636, -118.2281216), ('Foothill College', 37.3614878, -122.1283277), ('MiraCosta College', 33.1927582, -117.3093114), ('Antelope Valley College', 34.6777643, -118.1876041), ('Moorpark College', 34.3015682, -118.8364075), ('Mt. San Jacinto College', 33.80662210000001, -116.9694101), ('Cosumnes River College', 38.4541192, -121.4227382), ('Los Angeles Trade Technical College', 34.0311432, -118.2702767), ('Reedley College', 36.60818250000001, -119.4600934), ('Cabrillo College', 36.9876108, -121.9259014), ('Irvine Valley College', 33.676165, -117.7763241), ('Chabot College', 37.6427231, -122.1062344), ('Citrus College', 34.1333259, -117.8851136), ('Ventura College', 34.2761617, -119.2299773), ('Golden West College', 33.7339347, -118.0033108), ('San Bernardino Valley College', 34.086308, -117.3076518), ('Butte College', 39.6485275, -121.6449417), ('San Diego Miramar College', 32.9072307, -117.1193489), ('Victor Valley College', 34.4747209, -117.2615981), ('Laney College', 37.7945491, -122.261122), ('Santiago Canyon College', 37.3541079, -121.9552356), ('Allan Hancock College', 34.9446133, -120.4189337), ('West Los Angeles College', 34.0040139, -118.3868556), ('College of the Sequoias', 36.325102, -119.3149754), ('Coastline Community College', 33.7157019, -117.9293396), ('Ohlone College', 37.5293321, -121.9145556), ('Merced College', 37.3348354, -120.4761796), ('Clovis Community College', 36.887979, -119.732427), ('Los Angeles Harbor College', 33.7841338, -118.2840218), ('Skyline College', 37.6300657, -122.4659034), ('Norco College', 33.9174931, -117.5689082), ('West Valley College', 37.263434, -122.0100493), ('Solano Community College', 38.2352198, -122.119899), ('Monterey Peninsula College', 36.5893339, -121.8869455), ('San JosÃ© City College', 37.3146585, -121.9272308), ('Hartnell College', 36.6741645, -121.6676283), ('College of San Mateo', 37.535479, -122.3355121), ('College of the Desert', 33.7324231, -116.3872567), ('Cuesta College', 35.32924990000001, -120.7400729), ('Evergreen Valley College', 37.3011274, -121.7650792), ('Mission College', 37.3925485, -121.9828037), ('Los Angeles Mission College', 34.0522342, -118.2436849), ('Cuyamaca College', 32.7446539, -116.9404423), ('Las Positas College', 36.778261, -119.4179324), ('Los Medanos College', 38.0057947, -121.8608721), ('Shasta College', 40.6255781, -122.3180956), ('Moreno Valley College', 33.886786, -117.2029323), ('Folsom Lake College', 38.6619796, -121.1261936), ('Los Angeles Southwest College', 33.9292982, -118.3055411), ('Imperial Valley College', 32.8283376, -115.5035534), ('Compton College', 33.8774579, -118.2110328), ('Oxnard College', 34.1648731, -119.1557205), ('Yuba College', 39.2547027, -121.3998995), ('Contra Costa College', 37.9688909, -122.3400902), ('CaÃ±ada College', 37.4473859, -122.2652419), ('Berkeley City College', 36.778261, -119.4179324), ('Napa Valley College', 38.2742517, -122.2760808), ('College of Marin', 37.9557822, -122.5496479), ('Merritt College', 37.789553, -122.165612), ('Gavilan College', 36.9732557, -121.5685598), ('College of Alameda', 37.7823036, -122.2793551), ('Crafton Hills College', 34.0391513, -117.1012275), ('Taft College', 35.1492183, -119.4601285), ('College of the Redwoods', 40.698432, -124.1953753), ('Cerro Coso Community College', 35.5674569, -117.667777), ('West Hills College Lemoore', 36.2923855, -119.8238254), ('Porterville College', 36.0491632, -119.0143883), ('Mendocino College', 39.1895625, -123.2277897), ('Palo Verde College', 33.6610426, -114.6529049), ('Barstow Community College', 34.87031810000001, -117.0233643), ('West Hills College Coalinga', 36.1478043, -120.3570364), ('Woodland Community College', 38.6605655, -121.7356304), ('Columbia College', 38.0317977, -120.3885135), ('College of the Siskiyous', 41.4121709, -122.3902923), ('Lassen College', 40.4315267, -120.6325811), ('Lake Tahoe Community College', 38.9266515, -119.9725759), ('Copper Mountain College', 34.1410598, -116.2169342), ('Feather River College', 39.9530679, -120.9730115)]

In [61]:
cur.execute('SELECT * \
FROM cc_admissions')
print(cur.fetchall())

[(1, 'East Los Angeles College', 36606.0, 7090.0, 29516.0, 1945), (2, 'Santa Monica College', 29999.0, 10720.0, 19279.0, 1929), (3, 'American River College', 29701.0, 7560.0, 22141.0, 1955), (4, 'Santa Ana College', 28598.0, 3435.0, 25163.0, 1915), (5, 'Mount San Antonio College', 28481.0, 10499.0, 17982.0, 1946), (6, 'City College of San Francisco', 26706.0, 9198.0, 17508.0, 1935), (7, 'Pasadena City College', 25268.0, 9463.0, 15805.0, 1924), (8, 'Palomar College', 24665.0, 8252.0, 16413.0, 1946), (9, 'Fullerton College', 24301.0, 8440.0, 15861.0, 1913), (10, 'San Diego Mesa College', 24251.0, 6409.0, 17842.0, 1963), (11, 'Long Beach City College', 24020.0, 9530.0, 14490.0, 1927), (12, 'El Camino Community College District', 23996.0, 7866.0, 16130.0, 1947), (13, 'Sacramento City College', 23509.0, 6144.0, 17365.0, 1916), (14, 'De Anza College', 23261.0, 10774.0, 12487.0, 1967), (15, 'Santa Rosa Junior College', 22094.0, 6712.0, 15382.0, 1918), (16, 'Orange Coast College', 21886.0, 8497.0, 13389.0, 1947), (17, 'Cerritos College', 21404.0, 6958.0, 14446.0, 1955), (18, 'Fresno City College', 21344.0, 7815.0, 13529.0, 1910), (19, 'Saddleback College', 20871.0, 6334.0, 14537.0, 1968), (20, 'Diablo Valley College', 20286.0, 7690.0, 12596.0, 1949), (21, 'Los Angeles Pierce College', 20080.0, 4489.0, 15591.0, 1947), (22, 'Los Angeles City College', 19635.0, 4462.0, 15173.0, 1929), (23, 'Southwestern College', 19591.0, 7672.0, 11919.0, 1961), (24, 'Santa Barbara City College', 19331.0, 8516.0, 10815.0, 1909), (25, 'Chaffey College', 19211.0, 5664.0, 13547.0, 1883), (26, 'Los Angeles Valley College', 18762.0, 4526.0, 14236.0, 1949), (27, 'Grossmont College', 18618.0, 6654.0, 11964.0, 1961), (28, 'College of the Canyons', 18508.0, 6446.0, 12062.0, 1969), (29, 'Sierra College', 18374.0, 6951.0, 11423.0, 1936), (30, 'Riverside City College', 18165.0, 4863.0, 13302.0, 1916), (31, 'Bakersfield College', 17770.0, 5615.0, 12155.0, 1913), (32, 'San Joaquin Delta College', 17629.0, 7062.0, 10567.0, 1935), (33, 'Modesto Junior College', 17084.0, 6241.0, 10843.0, 1921), (34, 'Rio Hondo College', 16548.0, 4389.0, 12159.0, 1960), (35, 'San Diego City College', 16310.0, 3828.0, 12482.0, 1914), (36, 'Cypress College', 15881.0, 5079.0, 10802.0, 1966), (37, 'Glendale Community College', 15744.0, 7164.0, 8580.0, 1927), (38, 'Foothill College', 14814.0, 5266.0, 9548.0, 1957), (39, 'MiraCosta College', 14537.0, 6438.0, 8099.0, 1934), (40, 'Antelope Valley College', 14262.0, 4509.0, 9753.0, 1929), (41, 'Moorpark College', 14206.0, 5708.0, 8498.0, 1967), (42, 'Mt. San Jacinto College', 14170.0, 5105.0, 9065.0, 1962), (43, 'Cosumnes River College', 13949.0, 3333.0, 10616.0, 1970), (44, 'Los Angeles Trade Technical College', 13879.0, 3447.0, 10432.0, 1925), (45, 'Reedley College', 13807.0, 5328.0, 8479.0, 1926), (46, 'Cabrillo College', 13666.0, 4625.0, 9041.0, 1959), (47, 'Irvine Valley College', 13362.0, 4495.0, 8867.0, 1979), (48, 'Chabot College', 13142.0, 3939.0, 9203.0, 1961), (49, 'Citrus College', 12920.0, 4931.0, 7989.0, 1915), (50, 'Ventura College', 12908.0, 4387.0, 8521.0, 1925), (51, 'Golden West College', 12717.0, 4534.0, 8183.0, 1965), (52, 'San Bernardino Valley College', 12329.0, 4413.0, 7916.0, 1926), (53, 'Butte College', 12163.0, 5816.0, 6347.0, 1967), (54, 'San Diego Miramar College', 11891.0, 2271.0, 9620.0, 1969), (55, 'Victor Valley College', 11504.0, 4030.0, 7474.0, 1961), (56, 'Laney College', 11362.0, 1907.0, 9455.0, 1953), (57, 'Santiago Canyon College', 10939.0, 1938.0, 9001.0, 1985), (58, 'Allan Hancock College', 10885.0, 3395.0, 7490.0, 1920), (59, 'West Los Angeles College', 10767.0, 2160.0, 8607.0, 1969), (60, 'College of the Sequoias', 10720.0, 4928.0, 5792.0, 1926), (61, 'Coastline Community College', 10378.0, 1476.0, 8902.0, 1976), (62, 'Ohlone College', 10310.0, 3219.0, 7091.0, 1965), (63, 'Merced College', 10205.0, 4882.0, 5323.0, 1962), (64, 'Clovis Community College', 10139.0, 3432.0, 6323.0, 2007), (65, 'Los Angeles Harbor College', 10098.0, 2535.0, 7563.0, 1949), (66, 'Skyline College', 10067.0, 2598.0, 7469.0, 1969), (67, 'Norco College', 9648.0, 2270.0, 7378.0, 1991), (68, 'West Valley College', 9636.0, 3065.0, 6571.0, 1963), (69, 'Solano Community College', 9583.0, 3249.0, 6334.0, 1945), (70, 'Monterey Peninsula College', 9519.0, 2320.0, 7199.0, 1947), (71, 'San JosÃ© City College', 9446.0, 2432.0, 7014.0, 1921), (72, 'Hartnell College', 9439.0, 3413.0, 6026.0, 1920), (73, 'College of San Mateo', 9377.0, 2521.0, 6856.0, 1922), (74, 'College of the Desert', 9259.0, 3629.0, 5630.0, 1958), (75, 'Cuesta College', 9256.0, 3837.0, 5419.0, 1963), (76, 'Evergreen Valley College', 9211.0, 2789.0, 6422.0, 1975), (77, 'Mission College', 9130.0, 2417.0, 6713.0, 1975), (78, 'Los Angeles Mission College', 8990.0, 1941.0, 7049.0, 1975), (79, 'Cuyamaca College', 8859.0, 2099.0, 6760.0, 1978), (80, 'Las Positas College', 8631.0, 2923.0, 5708.0, 1964), (81, 'Los Medanos College', 8525.0, 2709.0, 5816.0, 1974), (82, 'Shasta College', 8479.0, 3817.0, 4662.0, 1950), (83, 'Moreno Valley College', 8420.0, 1976.0, 6444.0, 2010), (84, 'Folsom Lake College', 8034.0, 2017.0, 6017.0, 2004), (85, 'Los Angeles Southwest College', 7864.0, 1333.0, 6531.0, 1967), (86, 'Imperial Valley College', 7701.0, 3832.0, 3869.0, 1962), (87, 'Compton College', 7693.0, 1896.0, 5797.0, 1927), (88, 'Oxnard College', 6939.0, 1933.0, 5006.0, 1975), (89, 'Yuba College', 6874.0, 2672.0, 4202.0, 1927), (90, 'Contra Costa College', 6865.0, 2153.0, 4712.0, 1946), (91, 'CaÃ±ada College', 6620.0, 1202.0, 5418.0, 1968), (92, 'Berkeley City College', 6471.0, 1049.0, 5422.0, 1974), (93, 'Napa Valley College', 6308.0, 2376.0, 3932.0, 1942), (94, 'College of Marin', 6077.0, 1281.0, 4796.0, 1926), (95, 'Merritt College', 5887.0, 838.0, 5049.0, 1954), (96, 'Gavilan College', 5834.0, 1855.0, 3979.0, 1919), (97, 'College of Alameda', 5799.0, 716.0, 5083.0, 1968), (98, 'Crafton Hills College', 5697.0, 1991.0, 3706.0, 1972), (99, 'Taft College', 5444.0, 1193.0, 4251.0, 1922), (100, 'College of the Redwoods', 4938.0, 1901.0, 3037.0, 1964), (101, 'Cerro Coso Community College', 4523.0, 944.0, 3579.0, 1973), (102, 'West Hills College Lemoore', 4102.0, 1361.0, 2741.0, 2002), (103, 'Porterville College', 3810.0, 1662.0, 2148.0, 1927), (104, 'Mendocino College', 3729.0, 1256.0, 2473.0, 1973), (105, 'Palo Verde College', 3253.0, 424.0, 2829.0, 1947), (106, 'Barstow Community College', 3211.0, 1172.0, 2039.0, 1959), (107, 'West Hills College Coalinga', 3055.0, 951.0, 2104.0, 1932), (108, 'Woodland Community College', 2641.0, 830.0, 1811.0, 2008), (109, 'Columbia College', 2626.0, 843.0, 1783.0, 1968), (110, 'College of the Siskiyous', 2533.0, 1002.0, 1531.0, 1957), (111, 'Lassen College', 2494.0, 600.0, 1894.0, 1925), (112, 'Lake Tahoe Community College', 2426.0, 765.0, 1661.0, 1975), (113, 'Copper Mountain College', 1783.0, 750.0, 1033.0, 1966), (114, 'Feather River College', 1782.0, 636.0, 1146.0, 1968)]

In [59]:
df['Total enrollment'

0      36,606
1      29,999
2      29,701
3      28,598
4      28,481
        ...
109     2,533
110     2,494
111     2,426
112     1,783
113     1,782
Name: Total enrollment, Length: 114, dtype: object

#### _Relational Join Coordinate Data with Community College Admission Data_

In [45]:
#This is the Main (Merged) Dataset to perform Analysis on
cc_df = df.merge(api_df, how='inner', on='College')
cc_df.head()

,Ranking,College,Total enrollment,Full-time enrollment,Part-time enrollment,Founded,Lat,Lon
0,1,East Los Angeles College,"36,606","7,090","29,516",1945,34.041435,-118.150198
1,2,Santa Monica College,"29,999","10,720","19,279",1929,34.016781,-118.470693
2,3,American River College,"29,701","7,560","22,141",1955,38.651148,-121.346733
3,4,Santa Ana College,"28,598","3,435","25,163",1915,33.757971,-117.888884
4,5,Mount San Antonio College,"28,481","10,499","17,982",1946,34.048749,-117.842132

In [34]:
import requests 
API_key = 'AIzaSyAWXRek5w7WA4qithObH-inNzYL8UYGC0U'


city = 'Santa Monica College'
link = f'https://maps.googleapis.com/maps/api/geocode/json?address={city.replace(" ", "+")}&key={API_key}'
response = requests.get(link)
addy_data = response.json()

In [15]:
lat, lon = addy_data['results'][0]['geometry']['location']['lat'],addy_data['results'][0]['geometry']['location']['lng']

In [16]:
lat, lon

(34.0167814, -118.4706934)

In [46]:
import folium
map = folium.Map(location=[lat, lon], zoom_start=13)

for idx in range(len(api_df)):

# Add a marker at the coordinates
    marker = folium.Marker(location=[api_df['Lat'].iloc[idx], api_df['Lon'].iloc[idx]])
    marker.add_to(map)

# Display the map
map