In [3]:
import pandas as pd
def import_data():
    emission_df = pd.read_csv('CO2_emission.csv')
    return emission_df #Relational Column: 'Country Name'

In [4]:
import_data()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Samoa,WSM,East Asia & Pacific,CO2 emissions (metric tons per capita),0.552836,0.609756,0.604266,0.658221,0.592807,0.705675,...,1.066843,1.057703,1.048702,1.092498,1.240246,1.542099,1.586830,1.478626,1.522124,1.522124
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),0.567037,0.690937,0.704793,0.627105,0.653256,0.706081,...,0.963978,0.858491,1.106688,1.062211,0.511362,0.399364,0.359622,0.341068,0.380633,0.380633
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729799,6.424622,6.175430,6.219194,6.215847,6.378790,...,7.869816,8.077958,8.138264,8.212241,7.669938,7.563739,7.641675,7.515679,7.507736,7.507736
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.340930,0.349232,0.337224,0.289956,0.241270,0.234153,...,0.217497,0.278601,0.284058,0.304550,0.312355,0.325115,0.404068,0.445489,0.380717,0.380717
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585444,1.713321,1.694416,1.539741,1.417186,1.356619,...,0.884886,0.915735,0.919824,0.889104,0.899770,0.785441,0.726297,0.857411,0.802979,0.802979